#pragma once
enum TextureId {
	GSPRITESHEETTEXTURE,
	FIRSTMAP,
	GTIMER,
	GOOFCOUNTER,
	WELCOMEOBH,
	PRESSSTART,
	BIGLOGO,
	WALLTEXTURE,
	LAVA,
	CHECKCOIN,
	NEWLEVEL,
	TOTALTEXTURES
};
enum ObstacleId {
	GOODPLATFORMONE,
	GOODPLATFORMTWO,

	FLOORTWOGOODPLATFORMONE,
	FLOORTWOGOODPLATFORMTWO,
	FLOORTWOGOODPLATFORMTHREE,

	FLOORTHREEGOODPLATFORMONE,
	FLOORTHREEGOODPLATFORMTWO,

	BADPLATFORMONE,
	FLOORTWOBADPLATFORMONE,
	FLOORTWOBADPLATFORMTWO,

	TOTALOBSTACLES
};
enum Checkpoints {
	CHECKPOINTONE,
	TOTALCHECKPOINTS
};