#pragma once
enum TextureId {
	GSPRITESHEETTEXTURE,
	FIRSTMAP,
	GTIMER,
	WELCOMEOBH,
	PRESSSTART,
	BIGLOGO,
	TOTALTEXTURES
};
enum ObstacleId {
	GOODPLATFORMONE,
	GOODPLATFORMTWO,
	FLOORTWOGOODPLATFORMONE,
	FLOORTWOGOODPLATFORMTWO,
	BADPLATFORMONE,
	FLOORTWOBADPLATFORMONE,
	TOTALOBSTACLES
};